# Generated by Django 5.0.6 on 2026-02-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaturan', '0010_add_slip_gaji_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatecetak',
            name='jenis',
            field=models.CharField(choices=[('tagihan', 'Tagihan Sewa'), ('kwitansi', 'Kwitansi Pembayaran'), ('slip_gaji', 'Slip Gaji Karyawan')], max_length=20, unique=True, verbose_name='Jenis Dokumen'),
        ),
    ]
