# Generated by Django 5.0.6 on 2026-03-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaturan', '0011_alter_templatecetak_jenis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatecetak',
            name='jenis',
            field=models.CharField(choices=[('tagihan', 'Tagihan Sewa'), ('kwitansi', 'Kwitansi Pembayaran'), ('slip_gaji', 'Slip Gaji Karyawan'), ('export_excel', 'Template Export Excel'), ('export_pdf', 'Template Export PDF')], max_length=20, unique=True, verbose_name='Jenis Dokumen'),
        ),
    ]
