# Generated by Django 5.0.6 on 2026-03-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaturan', '0012_add_export_template_jenis'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodePembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Metode')),
                ('kode', models.CharField(max_length=20, unique=True, verbose_name='Kode')),
                ('nama_pemilik', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Pemilik')),
                ('deskripsi', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='metode_pembayaran/', verbose_name='Gambar/Logo')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Awal')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('diupdate_pada', models.DateTimeField(auto_now=True, verbose_name='Diupdate Pada')),
            ],
            options={
                'verbose_name': 'Metode Pembayaran',
                'verbose_name_plural': 'Metode Pembayaran',
                'ordering': ['nama'],
            },
        ),
    ]
