# Generated by Django 6.0.3 on 2026-04-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaturan', '0013_add_metode_pembayaran_simkos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengaturanperusahaan',
            name='auth_background_image',
            field=models.ImageField(blank=True, null=True, upload_to='pengaturan/auth/', verbose_name='Background Login/Register'),
        ),
        migrations.AddField(
            model_name='pengaturanperusahaan',
            name='auth_image',
            field=models.ImageField(blank=True, null=True, upload_to='pengaturan/auth/', verbose_name='Ilustrasi Login/Register'),
        ),
        migrations.AddField(
            model_name='pengaturanperusahaan',
            name='misc_background_image',
            field=models.ImageField(blank=True, null=True, upload_to='pengaturan/misc/', verbose_name='Background Error/Maintenance'),
        ),
        migrations.AddField(
            model_name='pengaturanperusahaan',
            name='misc_image',
            field=models.ImageField(blank=True, null=True, upload_to='pengaturan/misc/', verbose_name='Ilustrasi Error/Maintenance'),
        ),
        migrations.AlterField(
            model_name='pengaturanperusahaan',
            name='system_title',
            field=models.CharField(default='SIMKOS', max_length=200, verbose_name='Judul Sistem'),
        ),
        migrations.AlterField(
            model_name='templatecetak',
            name='footer_copyright',
            field=models.CharField(default='© 2026 SIMKOS', max_length=200, verbose_name='Footer Copyright'),
        ),
        migrations.AlterField(
            model_name='templatecetak',
            name='header_nama_perusahaan',
            field=models.CharField(default='SIMKOS', max_length=200, verbose_name='Nama Perusahaan'),
        ),
    ]
