# Generated by Django 6.0.3 on 2026-05-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaturan', '0014_pengaturanperusahaan_auth_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatecetak',
            name='jenis',
            field=models.CharField(choices=[('tagihan', 'Tagihan Sewa'), ('kwitansi', 'Kwitansi Pembayaran'), ('slip_gaji', 'Slip Gaji Karyawan'), ('expense', 'Bukti Pengeluaran Biaya'), ('export_excel', 'Template Export Excel'), ('export_pdf', 'Template Export PDF')], max_length=20, unique=True, verbose_name='Jenis Dokumen'),
        ),
    ]
