# Generated by Django 5.0.6 on 2026-02-26 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Penyewa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Lengkap')),
                ('nik', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='NIK (KTP)')),
                ('jenis_kelamin', models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1, null=True, verbose_name='Jenis Kelamin')),
                ('telepon', models.CharField(max_length=20, verbose_name='No. Telepon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('alamat_asal', models.TextField(blank=True, null=True, verbose_name='Alamat Asal')),
                ('pekerjaan', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pekerjaan')),
                ('foto_ktp', models.ImageField(blank=True, null=True, upload_to='penyewa/ktp/', verbose_name='Foto KTP')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='penyewa/foto/', verbose_name='Foto Penyewa')),
                ('kontak_darurat_nama', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nama Kontak Darurat')),
                ('kontak_darurat_telepon', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telepon Kontak Darurat')),
                ('kontak_darurat_hubungan', models.CharField(blank=True, max_length=50, null=True, verbose_name='Hubungan')),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('nonaktif', 'Nonaktif'), ('blacklist', 'Blacklist')], default='aktif', max_length=20, verbose_name='Status')),
                ('catatan', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penyewa_dibuat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Penyewa',
                'verbose_name_plural': 'Penyewa',
                'ordering': ['nama'],
            },
        ),
    ]
