# Generated by Django 5.0.6 on 2026-02-26 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipeKamar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Tipe')),
                ('harga_bulanan', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Harga per Bulan (Rp)')),
                ('fasilitas', models.TextField(blank=True, help_text='Pisahkan dengan koma. Contoh: AC, WiFi, Kamar Mandi Dalam', null=True, verbose_name='Fasilitas')),
                ('deskripsi', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipe Kamar',
                'verbose_name_plural': 'Tipe Kamar',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Properti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Properti')),
                ('tipe', models.CharField(choices=[('kost', 'Kost'), ('kontrakan', 'Kontrakan'), ('apartemen', 'Apartemen'), ('rumah', 'Rumah Sewa')], default='kost', max_length=20, verbose_name='Tipe Properti')),
                ('alamat', models.TextField(verbose_name='Alamat Lengkap')),
                ('kota', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kota/Kabupaten')),
                ('deskripsi', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='properti/', verbose_name='Foto Properti')),
                ('pemilik', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Pemilik')),
                ('telepon', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telepon')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properti_dibuat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Properti',
                'verbose_name_plural': 'Properti',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Kamar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_kamar', models.CharField(max_length=20, verbose_name='Nomor Kamar')),
                ('lantai', models.PositiveIntegerField(default=1, verbose_name='Lantai')),
                ('status', models.CharField(choices=[('tersedia', 'Tersedia'), ('terisi', 'Terisi'), ('maintenance', 'Perbaikan')], default='tersedia', max_length=20, verbose_name='Status')),
                ('fasilitas_tambahan', models.TextField(blank=True, null=True, verbose_name='Fasilitas Tambahan')),
                ('catatan', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
                ('properti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properti.properti', verbose_name='Properti')),
                ('tipe_kamar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properti.tipekamar', verbose_name='Tipe Kamar')),
            ],
            options={
                'verbose_name': 'Kamar',
                'verbose_name_plural': 'Kamar',
                'ordering': ['properti', 'nomor_kamar'],
                'unique_together': {('properti', 'nomor_kamar')},
            },
        ),
    ]
