# Generated by Django 5.0.6 on 2026-02-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kamar',
            name='height',
            field=models.IntegerField(default=80, verbose_name='Tinggi (denah)'),
        ),
        migrations.AddField(
            model_name='kamar',
            name='pos_x',
            field=models.IntegerField(default=0, verbose_name='Posisi X (denah)'),
        ),
        migrations.AddField(
            model_name='kamar',
            name='pos_y',
            field=models.IntegerField(default=0, verbose_name='Posisi Y (denah)'),
        ),
        migrations.AddField(
            model_name='kamar',
            name='width',
            field=models.IntegerField(default=100, verbose_name='Lebar (denah)'),
        ),
    ]
