# Generated by Django 6.0.3 on 2026-05-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_licenseconfig_app_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('properti', 'Properti'), ('penyewa', 'Penyewa'), ('sewa', 'Sewa'), ('biaya', 'Biaya'), ('hr', 'Karyawan KOS'), ('laporan', 'Laporan'), ('automation', 'Automasi Telegram'), ('user_management', 'Manajemen User'), ('access_control', 'Access Control'), ('activity_log', 'Log Aktivitas'), ('pengaturan', 'Pengaturan'), ('ai', 'AI Assistant')], db_index=True, max_length=50, verbose_name='Module'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Role'),
        ),
    ]
