# Generated by Django 5.0.6 on 2026-02-26 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('penyewa', '0001_initial'),
        ('properti', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KontrakSewa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_kontrak', models.CharField(max_length=50, unique=True, verbose_name='Nomor Kontrak')),
                ('tanggal_masuk', models.DateField(verbose_name='Tanggal Masuk')),
                ('tanggal_keluar', models.DateField(blank=True, null=True, verbose_name='Tanggal Keluar (Rencana)')),
                ('harga_sewa', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Harga Sewa per Bulan (Rp)')),
                ('deposit', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Deposit (Rp)')),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], default='aktif', max_length=20, verbose_name='Status')),
                ('catatan', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kontrak_dibuat', to=settings.AUTH_USER_MODEL)),
                ('kamar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kontrak', to='properti.kamar', verbose_name='Kamar')),
                ('penyewa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kontrak', to='penyewa.penyewa', verbose_name='Penyewa')),
            ],
            options={
                'verbose_name': 'Kontrak Sewa',
                'verbose_name_plural': 'Kontrak Sewa',
                'ordering': ['-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='TagihanSewa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_tagihan', models.CharField(max_length=50, unique=True, verbose_name='Nomor Tagihan')),
                ('periode_bulan', models.PositiveIntegerField(verbose_name='Bulan')),
                ('periode_tahun', models.PositiveIntegerField(verbose_name='Tahun')),
                ('jumlah', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Jumlah Tagihan (Rp)')),
                ('tanggal_jatuh_tempo', models.DateField(verbose_name='Jatuh Tempo')),
                ('status', models.CharField(choices=[('belum_bayar', 'Belum Bayar'), ('lunas', 'Lunas'), ('sebagian', 'Bayar Sebagian'), ('terlambat', 'Terlambat')], default='belum_bayar', max_length=20, verbose_name='Status')),
                ('catatan', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tagihan_dibuat', to=settings.AUTH_USER_MODEL)),
                ('kontrak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagihan', to='sewa.kontraksewa', verbose_name='Kontrak')),
            ],
            options={
                'verbose_name': 'Tagihan Sewa',
                'verbose_name_plural': 'Tagihan Sewa',
                'ordering': ['-periode_tahun', '-periode_bulan'],
                'unique_together': {('kontrak', 'periode_bulan', 'periode_tahun')},
            },
        ),
        migrations.CreateModel(
            name='PembayaranSewa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_pembayaran', models.CharField(max_length=50, unique=True, verbose_name='Nomor Pembayaran')),
                ('tanggal_bayar', models.DateField(verbose_name='Tanggal Bayar')),
                ('jumlah_bayar', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Jumlah Bayar (Rp)')),
                ('metode_bayar', models.CharField(choices=[('tunai', 'Tunai'), ('transfer', 'Transfer Bank'), ('ewallet', 'E-Wallet'), ('qris', 'QRIS')], default='tunai', max_length=20, verbose_name='Metode Bayar')),
                ('bukti_bayar', models.FileField(blank=True, null=True, upload_to='pembayaran/', verbose_name='Bukti Bayar')),
                ('catatan', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('dicatat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pembayaran_dicatat', to=settings.AUTH_USER_MODEL)),
                ('tagihan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pembayaran', to='sewa.tagihansewa', verbose_name='Tagihan')),
            ],
            options={
                'verbose_name': 'Pembayaran Sewa',
                'verbose_name_plural': 'Pembayaran Sewa',
                'ordering': ['-tanggal_bayar'],
            },
        ),
    ]
