# Generated by Django 6.0.3 on 2026-03-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0002_fix_metode_pembayaran_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagihansewa',
            name='jumlah_bayar',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Nominal deposit/bayar langsung saat buat tagihan', max_digits=12, verbose_name='Jumlah Bayar (Rp)'),
        ),
        migrations.AddField(
            model_name='tagihansewa',
            name='metode_pembayaran',
            field=models.CharField(blank=True, help_text='Metode pembayaran (Transfer, Tunai, dll)', max_length=50, null=True, verbose_name='Metode Pembayaran'),
        ),
    ]
