# Generated by Django 5.0.6 on 2026-02-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengaturantelegram',
            name='notif_pos',
        ),
        migrations.RemoveField(
            model_name='pengaturantelegram',
            name='notif_purchase_order',
        ),
        migrations.RemoveField(
            model_name='pengaturantelegram',
            name='notif_sales_order',
        ),
        migrations.AddField(
            model_name='pengaturantelegram',
            name='notif_gaji',
            field=models.BooleanField(default=True, verbose_name='Notifikasi Gaji Karyawan KOS'),
        ),
        migrations.AddField(
            model_name='pengaturantelegram',
            name='notif_kwitansi',
            field=models.BooleanField(default=True, verbose_name='Notifikasi Kwitansi Pembayaran'),
        ),
        migrations.AddField(
            model_name='pengaturantelegram',
            name='notif_tagihan',
            field=models.BooleanField(default=True, verbose_name='Notifikasi Tagihan Sewa'),
        ),
        migrations.AlterField(
            model_name='lognotifikasi',
            name='jenis_transaksi',
            field=models.CharField(choices=[('tagihan', 'Tagihan Sewa'), ('kwitansi', 'Kwitansi Pembayaran'), ('biaya', 'Biaya Operasional'), ('gaji', 'Gaji Karyawan KOS')], max_length=30, verbose_name='Jenis Transaksi'),
        ),
        migrations.AlterField(
            model_name='pengaturantelegram',
            name='notif_biaya',
            field=models.BooleanField(default=True, verbose_name='Notifikasi Biaya Operasional'),
        ),
        migrations.AlterField(
            model_name='templatepesan',
            name='jenis',
            field=models.CharField(choices=[('tagihan', 'Tagihan Sewa'), ('kwitansi', 'Kwitansi Pembayaran'), ('biaya', 'Biaya Operasional'), ('gaji', 'Gaji Karyawan KOS')], max_length=30, unique=True, verbose_name='Jenis Transaksi'),
        ),
    ]
