# Generated by Django 6.0.3 on 2026-05-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_penggajian_metode_pembayaran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensi',
            name='status',
            field=models.CharField(choices=[('hadir', 'Hadir'), ('terlambat', 'Terlambat'), ('izin', 'Izin'), ('sakit', 'Sakit'), ('alpha', 'Alpha'), ('cuti', 'Cuti'), ('libur', 'Libur')], db_index=True, default='hadir', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='tanggal',
            field=models.DateField(db_index=True, verbose_name='Tanggal'),
        ),
        migrations.AlterField(
            model_name='penggajian',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('diproses', 'Diproses'), ('dibayar', 'Dibayar'), ('batal', 'Batal')], db_index=True, default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
