# Generated by Django 5.0.6 on 2026-02-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biaya', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksibiaya',
            name='metode_pembayaran',
            field=models.CharField(blank=True, choices=[('tunai', 'Tunai'), ('transfer', 'Transfer Bank'), ('ewallet', 'E-Wallet'), ('qris', 'QRIS')], default='tunai', max_length=20, null=True, verbose_name='Metode Pembayaran'),
        ),
    ]
