# Generated by Django 5.0.6 on 2026-03-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biaya', '0002_transaksibiaya_metode_pembayaran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksibiaya',
            name='metode_pembayaran',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Metode Pembayaran'),
        ),
    ]
