# Generated by Django 6.0.3 on 2026-05-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biaya', '0003_fix_metode_pembayaran_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksibiaya',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Diajukan'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], db_index=True, default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='transaksibiaya',
            name='tanggal',
            field=models.DateField(db_index=True, verbose_name='Tanggal'),
        ),
    ]
