# Generated by Django 5.0.6 on 2026-02-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_avatar_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('SUPERUSER', 'Superuser - Full Access'), ('ADMIN', 'Admin - Limited Access'), ('USER', 'User - Read & Create Only'), ('KASIR', 'Kasir - POS Access Only')], default='USER', help_text='User role for access control', max_length=20, verbose_name='Role'),
        ),
    ]
