# Generated by Django 5.0.6 on 2026-02-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='forget_password_token_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
