# Generated by Django 5.0.6 on 2026-02-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_forget_password_token_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[], default='USER', help_text='User role for access control', max_length=50, verbose_name='Role'),
        ),
    ]
